<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Подтверждение регистрации</title>
    <style>
        h1 {
            color: cadetblue;
        }

        h2 {
            color: red;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию:</h1>
<img src="https://na-dache.pro/uploads/posts/2021-05/1620605630_16-p-dom-na-beregu-reki-foto-21.jpg" alt="">
<h2><a href="http://localhost:8080/account/confirm/${confirm_id}">Подтвердите почту</a></h2>
</body>
</html>